### ISSUE TITLE
Several Errors

### ISSUE THREAD

**Issue by PKMWM1** [suloku/BW_tool#4]
I don't know if this program is still being updated, but if it is, there are two major problems that I'm having with the program involving Join Avenue and 3ds link editing. Whenever I try to open either tab in my game, it just throws the following errors and then I can't edit them at all. This is really annoying and inconveniencing.
Heres the Join Avenue error Pic and the expanded info it throws:
![error pic 1](https://cloud.githubusercontent.com/assets/20786416/26444453/be9a6d48-40f9-11e7-985f-e50028a6ae09.png)
************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '4' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at BW_tool.Join_avenue.load_shop()
   at BW_tool.Join_avenue.load_data()
   at BW_tool.Join_avenue..ctor()
   at BW_tool.MainForm.Join_butClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BW_tool
    Assembly Version: 1.0.6291.43112
    Win32 Version: 1.0.6291.43112
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/DS%20Pokemon%20Saves/Gen%205%20Extra%20Features%20Save%20editor/BW_tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
And then the one for 3DS link:
![error pic 1](https://cloud.githubusercontent.com/assets/20786416/26444558/28634e70-40fa-11e7-9629-3deb14c99fde.png)
************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '154' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at BW_tool.DreamRadar.load_data()
   at BW_tool.DreamRadar.AllmodeCheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at BW_tool.DreamRadar..ctor()
   at BW_tool.MainForm.Dr_butClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BW_tool
    Assembly Version: 1.0.6291.43112
    Win32 Version: 1.0.6291.43112
    CodeBase: file:///C:/Users/Alec/Desktop/3DS%20Editing/DS%20Pokemon%20Saves/Gen%205%20Extra%20Features%20Save%20editor/BW_tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

**Comment by suloku** [comment]
Could you upload your savegame? I'm not currently working on this, but bugfixing/making sure the current features work as intended is something I want.

**Comment by SkyDragoon** [comment]
First of all, thank you so much for this tool.
I have the error only when going to Dream Radar option

![untitled](https://user-images.githubusercontent.com/30781477/29006707-6a224d18-7ac3-11e7-8a4b-59f33c719e4e.png)

here is my safe file

[Pokemon Black 2.zip](https://github.com/suloku/BW_tool/files/1203403/Pokemon.Black.2.zip)

**Comment by suloku** [comment]
Dream radar is fixed in latest release
https://github.com/suloku/BW_tool/releases/tag/20211313_21124

Unfortunately join avenue still requires research (the actual error might just be some bug in the code like with dream radar).

**Comment by amorillas19** [comment]
Hi, are you still developing and fixing bugs? Because, I had the exact same error trying to look at my Shops NPC's, but also if I want to add new some visitors using the "Visitor" page, the program doesn't save any information you put in there. 

Also, if you want to make a .pjv file with the information you made on that page, and exporting the data from the "Visitor" to a .pjv file, you create an empty file, without any info. So you can't import "customs" .pjv files. Only your visitor example files work as intended, and also you can modify them trough hex, and effectively you can see some changes when you load "DAVE.pjv" file for example.

Here are some pictures

![Dave-edited](https://user-images.githubusercontent.com/60206580/124403256-cc7c2980-dd0b-11eb-9412-363cb5d919d5.png)

This is Dave.pjv file edited 

![2](https://user-images.githubusercontent.com/60206580/124403269-e4ec4400-dd0b-11eb-900f-a0cea3f98895.png)

Which effectively works.

![3](https://user-images.githubusercontent.com/60206580/124403283-fc2b3180-dd0b-11eb-936c-08d89fd96adf.png)

But this are my own created pjv files. They're empty
